services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /app
    volumes:
      - ./homify:/app
    command: ["python", "manage.py", "runserver", "0.0.0.0:8000"]
    ports:
      - "8001:8000"
    depends_on:
      - db
    environment:
      - "DATABASE_URL=postgres://postgres:mypassword@db:5432/mydb"
    
  db:
    image: postgis/postgis:16-3.4
    volumes: 
      - postgres_data_homify:/var/lib/postgresql/data/
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydb

volumes:
  postgres_data_homify: