# Generated by Django 5.2.4 on 2025-08-18 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("listings", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="property",
            name="property_type",
            field=models.CharField(
                choices=[
                    ("house", "House"),
                    ("boarding_hosuse", "Boarding House"),
                    ("apartment", "Apartment"),
                    ("condo", "Condominium"),
                    ("lot", "Lot"),
                    ("commercial_lot", "Commercial Lot"),
                    ("office", "Office Space"),
                ],
                max_length=50,
            ),
        ),
    ]
