# Generated by Django 5.2.4 on 2025-08-18 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("listings", "0002_alter_property_property_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="property",
            name="floo_storey",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
