# Generated by Django 5.2.4 on 2025-08-18 03:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("listings", "0003_property_floo_storey"),
    ]

    operations = [
        migrations.RenameField(
            model_name="property",
            old_name="floo_storey",
            new_name="floor_storey",
        ),
    ]
