# Generated by Django 5.2.4 on 2025-08-18 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("listings", "0004_rename_floo_storey_property_floor_storey"),
    ]

    operations = [
        migrations.AddField(
            model_name="property",
            name="available_unit",
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
        migrations.AlterField(
            model_name="property",
            name="floor_storey",
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
    ]
