# Generated by Django 4.2.23 on 2025-08-20 18:52

import django.contrib.gis.db.models.fields
import django.contrib.postgres.indexes
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("listings", "0005_property_available_unit_alter_property_floor_storey"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="property",
            name="latitude",
        ),
        migrations.RemoveField(
            model_name="property",
            name="longitude",
        ),
        migrations.AddField(
            model_name="property",
            name="geom",
            field=django.contrib.gis.db.models.fields.PointField(
                blank=True, null=True, srid=4326
            ),
        ),
        migrations.AddIndex(
            model_name="property",
            index=models.Index(fields=["geom"], name="listings_pr_geom_453920_idx"),
        ),
        migrations.AddIndex(
            model_name="property",
            index=django.contrib.postgres.indexes.GistIndex(
                fields=["geom"], name="listings_pr_geom_3abb03_gist"
            ),
        ),
    ]
