# Generated by Django 4.2.23 on 2025-08-24 08:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "listings",
            "0006_remove_property_latitude_remove_property_longitude_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="property",
            name="image",
        ),
    ]
