# Generated by Django 4.2.23 on 2025-08-24 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("listings", "0008_property_image"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="property",
            name="image",
        ),
        migrations.AlterField(
            model_name="property",
            name="floor_area",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="property",
            name="price",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
