# Generated by Django 5.2.5 on 2025-09-08 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0009_remove_property_image_alter_property_floor_area_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='category',
            field=models.CharField(choices=[('rent', 'Rent'), ('sell', 'Sell')], default='residential', max_length=20),
        ),
        migrations.AlterField(
            model_name='property',
            name='property_type',
            field=models.CharField(choices=[('house', 'House'), ('boarding_house', 'Boarding House'), ('apartment', 'Apartment'), ('condo', 'Condominium'), ('office', 'Office Space')], max_length=50),
        ),
    ]
