# Generated by Django 5.2.5 on 2025-09-11 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0010_alter_property_category_alter_property_property_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='property',
            old_name='parking_spaces',
            new_name='number_of_rooms',
        ),
        migrations.AddField(
            model_name='property',
            name='address_city',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
