# Generated by Django 5.2.5 on 2025-09-12 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0011_rename_parking_spaces_property_number_of_rooms_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Amenity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='property',
            name='amenities',
            field=models.ManyToManyField(related_name='listings', to='listings.amenity'),
        ),
    ]
